// <auto-generated />
using System;
using CodePrintManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodePrintManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808075447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CodePrintManager.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProductId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("CodePrintManager.Domain.Entities.Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportBatch")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Available");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeText")
                        .IsUnique();

                    b.HasIndex("JobId");

                    b.HasIndex("Status");

                    b.HasIndex("ProductId", "Status");

                    b.ToTable("codes", (string)null);
                });

            modelBuilder.Entity("CodePrintManager.Domain.Entities.PrintJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodesConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Preparing");

                    b.Property<int?>("TotalBaseline")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId")
                        .IsUnique()
                        .HasFilter("[Status] IN ('Preparing', 'Ready', 'Printing')");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("[Status] IN ('Preparing', 'Ready', 'Printing')");

                    b.HasIndex("Status");

                    b.ToTable("print_jobs", (string)null);
                });

            modelBuilder.Entity("CodePrintManager.Domain.Entities.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdapterType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("savema_tto");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(9100);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("printers", (string)null);
                });

            modelBuilder.Entity("CodePrintManager.Domain.Entities.ProductNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLeaf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrinterCsvName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateFile")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("product_nodes", (string)null);
                });

            modelBuilder.Entity("CodePrintManager.Domain.Entities.Code", b =>
                {
                    b.HasOne("CodePrintManager.Domain.Entities.PrintJob", "Job")
                        .WithMany("Codes")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CodePrintManager.Domain.Entities.ProductNode", "Product")
                        .WithMany("Codes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CodePrintManager.Domain.Entities.PrintJob", b =>
                {
                    b.HasOne("CodePrintManager.Domain.Entities.Printer", "Printer")
                        .WithMany("PrintJobs")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodePrintManager.Domain.Entities.ProductNode", "Product")
                        .WithMany("PrintJobs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Printer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CodePrintManager.Domain.Entities.ProductNode", b =>
                {
                    b.HasOne("CodePrintManager.Domain.Entities.ProductNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CodePrintManager.Domain.Entities.PrintJob", b =>
                {
                    b.Navigation("Codes");
                });

            modelBuilder.Entity("CodePrintManager.Domain.Entities.Printer", b =>
                {
                    b.Navigation("PrintJobs");
                });

            modelBuilder.Entity("CodePrintManager.Domain.Entities.ProductNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Codes");

                    b.Navigation("PrintJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
